from typing import Any

from django.core.management.base import BaseCommand

from api.models import Direction
from api.models import RecommendedCourse

data = [
    # class 0
    {
        "num": "1",
        "recommended_courses_num": "2",
        "class_level": "0",
        "code_courses": "Rb0",
        "course_direction": "Робототехника",
        "course_name": "Теперь я знаю!",
        "course_url": "https://iteen.by/programs/doshkolniki-6-7-let/"
        "robototekhnika-doshkolniki-class-ek/",
        "course_start": None,
        "number_hours": "96",
        "price": "960,00",
        "recommended_courses": "Cs0",
    },
    {
        "num": "2",
        "recommended_courses_num": "4",
        "class_level": "0",
        "code_courses": "Cs0",
        "course_direction": "Computer science",
        "course_name": "Ступенька в ИТ-мир",
        "course_url": "https://iteen.by/programs/doshkolniki-6-7-let/"
        "computer-science-doshkolniki-0-class/",
        "course_start": None,
        "number_hours": "128",
        "price": "1280,00",
        "recommended_courses": "Rb1",
    },
    # class 1
    {
        "num": "3",
        "recommended_courses_num": "6",
        "class_level": "1",
        "code_courses": "Rb1",
        "course_direction": "Робототехника",
        "course_name": "Lego: простые механизмы + "
        "Lego занимательная математика",
        "course_url": "https://iteen.by/programs/1-class/" "robotics-1-klass/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Rb2",
    },
    {
        "num": "4",
        "recommended_courses_num": "7",
        "class_level": "1",
        "code_courses": "Rb1",
        "course_direction": "Робототехника",
        "course_name": "Lego: простые механизмы + Lego: "
        "технология и основы механики",
        "course_url": "https://iteen.by/programs/1-class/"
        "robototekhnika-1-klass/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Rb2",
    },
    {
        "num": "5",
        "recommended_courses_num": "6",
        "class_level": "1",
        "code_courses": "Cs1",
        "course_direction": "Computer science",
        "course_name": "IT-старт",
        "course_url": "https://iteen.by/programs/1-class/"
        "computer-science-1-class/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Rb2",
    },
    # class 2
    {
        "num": "6",
        "recommended_courses_num": "7",
        "class_level": "2",
        "code_courses": "Rb2",
        "course_direction": "Робототехника",
        "course_name": "Lego WeDo 1.2 + Юный программист в Scratch",
        "course_url": "https://iteen.by/programs/2-class/robotics-2-klass/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Rb3",
    },
    {
        "num": "7",
        "recommended_courses_num": "10",
        "class_level": "2",
        "code_courses": "Rb2",
        "course_direction": "Робототехника",
        "course_name": "Lego WeDo 2.0 + Юный программист в Scratch",
        "course_url": "https://iteen.by/programs/2-class/robotics-2-class/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Rb3",
    },
    {
        "num": "8",
        "recommended_courses_num": "9",
        "class_level": "2",
        "code_courses": "3d2",
        "course_direction": "Робототехника",
        "course_name": "Lego Digital Designer + Lego: "
        "занимательная математика",
        "course_url": None,
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Sr2",
    },
    {
        "num": "9",
        "recommended_courses_num": "16",
        "class_level": "2",
        "code_courses": "Sr2",
        "course_direction": "Робототехника",
        "course_name": "Спортивная робототехника. Elementary",
        "course_url": "https://iteen.by/programs/2-class/"
        "sportivnaya-robototekhnika-2-klass/",
        "course_start": None,
        "number_hours": "96",
        "price": "1728,00",
        "recommended_courses": "Sr2",
    },
    # class 3
    {
        "num": "10",
        "recommended_courses_num": "17",
        "class_level": "3",
        "code_courses": "Rb3",
        "course_direction": "Робототехника",
        "course_name": "Scratch-анимация + Lego SPIKE Prime",
        "course_url": "https://iteen.by/programs/3-class/"
        "robototekhnika-3-klass/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Rb4",
    },
    {
        "num": "11",
        "recommended_courses_num": "12",
        "class_level": "3",
        "code_courses": "Rb3",
        "course_direction": "Робототехника",
        "course_name": "Scratch анимация + Lego WeDo 2.0",
        "course_url": "https://iteen.by/programs/3-class/" "robotics-3-class/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Tm3",
    },
    {
        "num": "12",
        "recommended_courses_num": "19",
        "class_level": "3",
        "code_courses": "Tm3",
        "course_direction": "Техномейкерство",
        "course_name": "Как все устроено (занимательная физика) "
        "+ Робототехника (WeDo 2.0)",
        "course_url": "https://iteen.by/programs/3-class/"
        "technoligist-3-class/",
        "course_start": None,
        "number_hours": "64",
        "price": "960,00",
        "recommended_courses": "Tm4",
    },
    {
        "num": "13",
        "recommended_courses_num": "14",
        "class_level": "3",
        "code_courses": "Gd3",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Minecraft Building",
        "course_url": "https://iteen.by/programs/3-class/"
        "programming-and-game-dev-3-class/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Gd4",
    },
    {
        "num": "14",
        "recommended_courses_num": "20",
        "class_level": "3",
        "code_courses": "Gd3",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Занимательное программирование:"
        " Scratch + Kodu Game Lab",
        "course_url": "https://iteen.by/programs/3-class/"
        "programmirovanie-skgl-3-klass/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Gd3",
    },
    {
        "num": "15",
        "recommended_courses_num": "22",
        "class_level": "3",
        "code_courses": "Ms3",
        "course_direction": "Дизайн",
        "course_name": "Студия плоскостной анимации",
        "course_url": None,
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Ms4",
    },
    {
        "num": "16",
        "recommended_courses_num": "23",
        "class_level": "3",
        "code_courses": "Sr2",
        "course_direction": "Робототехника",
        "course_name": "Спортивная робототехника. Elementary",
        "course_url": "https://iteen.by/programs/3-class/sportivnaya-"
        "robototekhnika-3-klass/",
        "course_start": None,
        "number_hours": "96",
        "price": "1728,00",
        "recommended_courses": "Sr2",
    },
    # class 4
    {
        "num": "17",
        "recommended_courses_num": "18",
        "class_level": "4",
        "code_courses": "Rb4",
        "course_direction": "Робототехника",
        "course_name": "LEGO Education SPIKE Prime",
        "course_url": "https://iteen.by/programs/4-class/robotics-4-class/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Sr5",
    },
    {
        "num": "18",
        "recommended_courses_num": "23",
        "class_level": "4",
        "code_courses": "Rb4",
        "course_direction": "Робототехника",
        "course_name": "Lego WeDo 2.0: Dino Park +EV3 (базовые модели)",
        "course_url": "https://iteen.by/programs/4-class/robotiks-4-class/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Sr5",
    },
    {
        "num": "19",
        "recommended_courses_num": "31",
        "class_level": "4",
        "code_courses": "Tm4",
        "course_direction": "Техномейкерство",
        "course_name": "Юный программист-конструктор: Scratch + "
        "программирование микроконтроллера Micro:Bit",
        "course_url": "https://iteen.by/programs/4-class/"
        "technoligist-4-class/",
        "course_start": None,
        "number_hours": "64",
        "price": "960,00",
        "recommended_courses": "Tm5",
    },
    {
        "num": "20",
        "recommended_courses_num": "27",
        "class_level": "4",
        "code_courses": "Gd4",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Minecraft Coding",
        "course_url": "https://iteen.by/programs/4-class/programming-and-"
        "game-dev-4-class/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Gd5",
    },
    {
        "num": "21",
        "recommended_courses_num": "28",
        "class_level": "4",
        "code_courses": "Gd4",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Minecraft Building",
        "course_url": "https://iteen.by/programs/4-class/programming-and-"
        "game-dev-m-4-class/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Gd5",
    },
    {
        "num": "22",
        "recommended_courses_num": "29",
        "class_level": "4",
        "code_courses": "Ms4",
        "course_direction": "Дизайн",
        "course_name": "Студия объемной анимации",
        "course_url": "https://iteen.by/programs/4-class/design-ms-4-class/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Ms5",
    },
    {
        "num": "23",
        "recommended_courses_num": "30",
        "class_level": "4",
        "code_courses": "Sr2",
        "course_direction": "Робототехника",
        "course_name": "Спортивная робототехника. Elementary",
        "course_url": "https://iteen.by/programs/4-class/sportivnaya-r"
        "obototekhnika-4-klass/",
        "course_start": None,
        "number_hours": "96",
        "price": "1728,00",
        "recommended_courses": "Sr5",
    },
    # class 5
    {
        "num": "24",
        "recommended_courses_num": "30",
        "class_level": "5",
        "code_courses": "Rb5",
        "course_direction": "Робототехника",
        "course_name": "LEGO Mindstorms Education EV3",
        "course_url": None,
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Sr5",
    },
    {
        "num": "25",
        "recommended_courses_num": "31",
        "class_level": "5",
        "code_courses": "4k5",
        "course_direction": "Авмамодели_БПЛА",
        "course_name": "Квадрокоптеры для начинающих",
        "course_url": "https://iteen.by/programs/5-6-class/"
        "kvadrokoptery-5-6-klass/",
        "course_start": None,
        "number_hours": "96",
        "price": "1440,00",
        "recommended_courses": "Tm5",
    },
    {
        "num": "26",
        "recommended_courses_num": "29",
        "class_level": "5",
        "code_courses": "Кg5",
        "course_direction": "Дизайн",
        "course_name": "Основы компьютерной графики",
        "course_url": "https://iteen.by/programs/5-6-class/"
        "design-ma-5-6-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Ms5",
    },
    {
        "num": "27",
        "recommended_courses_num": "33",
        "class_level": "5",
        "code_courses": "Gd5",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Minecraft: программирование на Python",
        "course_url": "https://iteen.by/programs/5-6-class/"
        "programming-and-game-dev-minecraft-5-6-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Gd6",
    },
    {
        "num": "28",
        "recommended_courses_num": "32",
        "class_level": "5",
        "code_courses": "Gd5",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Minecraft: Code Master",
        "course_url": "https://iteen.by/programs/5-6-class/"
        "programmirovanie-minecraft-5-klass/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Gd6",
    },
    {
        "num": "29",
        "recommended_courses_num": "34",
        "class_level": "5",
        "code_courses": "Ms5",
        "course_direction": "Дизайн",
        "course_name": "Студия компьютерной анимации",
        "course_url": "https://iteen.by/programs/"
        "5-6-class/design-5-6-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Mg7",
    },
    {
        "num": "30",
        "recommended_courses_num": "36",
        "class_level": "5",
        "code_courses": "Sr5",
        "course_direction": "Робототехника",
        "course_name": "Спортивная робототехника. Junior",
        "course_url": "https://iteen.by/programs/5-6-class/"
        "sportivnaya-robototekhnika-j-5-6-klass/",
        "course_start": None,
        "number_hours": "192",
        "price": "3264,00",
        "recommended_courses": "Sr7",
    },
    # class 6
    {
        "num": "31",
        "recommended_courses_num": "37",
        "class_level": "6",
        "code_courses": "Tm5",
        "course_direction": "Техномейкерство",
        "course_name": "Юный программист-конструктор: "
        "Программирование микроконтроллера Micro:Bit+Python",
        "course_url": "https://iteen.by/programs/5-6-class/"
        "technoligist-5-6-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1440,00",
        "recommended_courses": "Tm7",
    },
    {
        "num": "32",
        "recommended_courses_num": "39",
        "class_level": "6",
        "code_courses": "Gd5",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Minecraft Python Coding",
        "course_url": "https://iteen.by/programs/5-6-class/"
        "programming-and-game-dev-minecraft-5-6-class/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Pt7",
    },
    {
        "num": "33",
        "recommended_courses_num": "41",
        "class_level": "6",
        "code_courses": "GdRx5",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Создание игр в Roblox Studio",
        "course_url": "https://iteen.by/programs/5-6-class/"
        "programming-and-game-dev-rs-5-6-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Gd7",
    },
    {
        "num": "34",
        "recommended_courses_num": "66",
        "class_level": "6",
        "code_courses": "Кg5",
        "course_direction": "Дизайн",
        "course_name": "Основы компьютерной графики",
        "course_url": "https://iteen.by/programs/5-6-class/"
        "design-ma-5-6-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Di8",
    },
    {
        "num": "35",
        "recommended_courses_num": "41",
        "class_level": "6",
        "code_courses": "Pr5",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Scratch: разработка браузерных и мобильных игр",
        "course_url": None,
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Gd7",
    },
    {
        "num": "36",
        "recommended_courses_num": "39",
        "class_level": "6",
        "code_courses": "Sr7",
        "course_direction": "Робототехника",
        "course_name": "Спортивная робототехника. Senior",
        "course_url": "https://iteen.by/programs/7-8-class/"
        "sportivnaya-robototekhnika-s-7-8-klass/",
        "course_start": None,
        "number_hours": "192",
        "price": "3264,00",
        "recommended_courses": "Pt7",
    },
    # class 7
    {
        "num": "37",
        "recommended_courses_num": "39",
        "class_level": "7",
        "code_courses": "Tm7",
        "course_direction": "Техномейкерство",
        "course_name": "Изобретатель: 3d-печать + "
        "умная электроника на основе Arduino",
        "course_url": "https://iteen.by/programs/7-8-class/"
        "technoligist-7-8-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1440,00",
        "recommended_courses": "Pt7",
    },
    {
        "num": "38",
        "recommended_courses_num": "66",
        "class_level": "7",
        "code_courses": "Mg7",
        "course_direction": "Дизайн",
        "course_name": "MagicArt: Photoshop + Illustrator",
        "course_url": "https://iteen.by/programs/7-8-class/"
        "design-ma-7-8-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Di8",
    },
    {
        "num": "39",
        "recommended_courses_num": "45",
        "class_level": "7",
        "code_courses": "Pt7",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Основы программирования на Python. Уровень 1",
        "course_url": "https://iteen.by/programs/7-8-class/"
        "programming-and-game-dev-python-7-8-class7765/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Pt8",
    },
    {
        "num": "40",
        "recommended_courses_num": "45",
        "class_level": "7",
        "code_courses": "Pt7",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Практическое программирование на Python",
        "course_url": "https://iteen.by/programs/7-8-class/"
        "programming-p-7-8-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Pt8",
    },
    {
        "num": "41",
        "recommended_courses_num": "46",
        "class_level": "7",
        "code_courses": "Gd7",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Разработка игр и приложений в Unity. "
        "Начинающий гейм-разработчик. Уровень 1",
        "course_url": "https://iteen.by/programs/7-8-class/"
        "programming-and-game-dev-7-8-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Gd8",
    },
    {
        "num": "42",
        "recommended_courses_num": "47",
        "class_level": "7",
        "code_courses": "2d/3d8",
        "course_direction": "Дизайн",
        "course_name": "2D- и 3D-графика",
        "course_url": "https://iteen.by/programs/7-8-class/"
        "design-g-7-8-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Bn9",
    },
    # class 8
    {
        "num": "43",
        "recommended_courses_num": "53",
        "class_level": "8",
        "code_courses": "Wb7",
        "course_direction": "Web-технологии",
        "course_name": "Основы веб-разработки и создание веб-игры на "
        "JavaScript",
        "course_url": "https://iteen.by/programs/7-8-class/web-"
        "tekhnologii-7-8-klass/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Wb9",
    },
    {
        "num": "44",
        "recommended_courses_num": "45",
        "class_level": "8",
        "code_courses": "Pt7",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Основы программирования на Python. Уровень 1.",
        "course_url": "https://iteen.by/programs/7-8-class/programming-"
        "and-game-dev-python-7-8-class7765/",
        "course_start": None,
        "number_hours": "64",
        "price": "896,00",
        "recommended_courses": "Pt8",
    },
    {
        "num": "45",
        "recommended_courses_num": "59",
        "class_level": "8",
        "code_courses": "Pt8",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Прикладное программирование на Python. Уровень 2.",
        "course_url": "https://iteen.by/programs/7-8-cla"
        "ss/programming-and-game-dev-8-grade/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Pt11",
    },
    {
        "num": "46",
        "recommended_courses_num": "65",
        "class_level": "8",
        "code_courses": "Gd8",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Разработка игр и приложений в Unity. "
        "Продвинутый разработчик мобильных, VR- и "
        "AR-приложений и "
        "игр. Уровень 2.",
        "course_url": "https://iteen.by/programs/9-10-class/prog"
        "ramming-and-game-dev-9-10-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "PLab10",
    },
    # class 9
    {
        "num": "47",
        "recommended_courses_num": "75",
        "class_level": "9",
        "code_courses": "Mg9",
        "course_direction": "Дизайн",
        "course_name": "MagicArt: Photoshop + Illustrator",
        "course_url": "https://iteen.by/programs/9-10-class/"
        "design-ma-9-10-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Sm9",
    },
    {
        "num": "48",
        "recommended_courses_num": "65",
        "class_level": "9",
        "code_courses": "Sr7",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Спортивная робототехника. Senior.",
        "course_url": "https://iteen.by/programs/9-10-class/"
        "sportivnaya-robototekhnika-s-9-10-klass/",
        "course_start": None,
        "number_hours": "192",
        "price": "3264,00",
        "recommended_courses": "PLab10",
    },
    {
        "num": "49",
        "recommended_courses_num": "58",
        "class_level": "9",
        "code_courses": "Pt9",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Основы программирования на Python. Уровень 1.",
        "course_url": "https://iteen.by/programs/9-10-class/programming"
        "-and-game-dev-python-9-10-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Pt10",
    },
    {
        "num": "50",
        "recommended_courses_num": "54",
        "class_level": "9",
        "code_courses": "Gd9",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Разработка игр и приложений в Unity. Начинающий "
        "гейм-разработчик. Уровень 1.",
        "course_url": "https://iteen.by/programs/9-10-class/programming-"
        "and-game-dev-u1-9-10-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Gd10",
    },
    # 10 class
    {
        "num": "51",
        "recommended_courses_num": "62",
        "class_level": "10",
        "code_courses": "Bn9",
        "course_direction": "Дизайн",
        "course_name": "Основы 3D-графики в Blender",
        "course_url": "https://iteen.by/programs/"
        "9-10-class/dizayn-9-10-klass/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Ux9",
    },
    # empty
    {
        "num": "52",
        "recommended_courses_num": "51",
        "class_level": "10",
        "code_courses": "Mt9",
        "course_direction": "Дизайн",
        "course_name": "Моушн-дизайн в Adobe After Effects",
        "course_url": "https://iteen.by/programs/"
        "9-10-class/dizayn-md-9-10-klass/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Bn9",
    },
    {
        "num": "53",
        "recommended_courses_num": "60",
        "class_level": "10",
        "code_courses": "Wb9",
        "course_direction": "Web-технологии",
        "course_name": "Front-end разработка: HTML, CSS, JavaScript",
        "course_url": "https://iteen.by/programs/"
        "9-10-class/web-tekhnologii-9-10-klass/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Php9",
    },
    {
        "num": "54",
        "recommended_courses_num": "67",
        "class_level": "10",
        "code_courses": "Gd10",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Разработка игр и приложений в Unity. Продвинутый "
        "разработчик мобильных, VR- и AR-приложений и игр. Уровень 2",
        "course_url": "https://iteen.by/programs/"
        "9-10-class/programming-and-game-dev-9-10-class/",
        "course_start": None,
        "number_hours": "128",
        "price": "2389,00",
        "recommended_courses": "GD1",
    },
    {
        "num": "55",
        "recommended_courses_num": "68",
        "class_level": "10",
        "code_courses": "Cd9",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Основы программирования на С++",
        "course_url": "https://iteen.by/programs/"
        "9-10-class/programming-and-game-dev-c-9-10-class/",
        "course_start": None,
        "number_hours": "128",
        "price": "2389,00",
        "recommended_courses": "CD1",
    },
    {
        "num": "56",
        "recommended_courses_num": "69",
        "class_level": "10",
        "code_courses": "Jv10",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Основы программирования на Java",
        "course_url": None,
        "course_start": None,
        "number_hours": "112",
        "price": "1999,00",
        "recommended_courses": "JC1",
    },
    {
        "num": "57",
        "recommended_courses_num": "65",
        "class_level": "10",
        "code_courses": "Pr7",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Практическое программирование",
        "course_url": "https://iteen.by/programs/"
        "9-10-class/programming-p-9-10-class/",
        "course_start": None,
        "number_hours": None,
        "price": None,
        "recommended_courses": "PLab10",
    },
    {
        "num": "58",
        "recommended_courses_num": "59",
        "class_level": "10",
        "code_courses": "Pt10",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Прикладное программирование на Python. Уровень 2",
        "course_url": "https://iteen.by/programs/"
        "9-10-class/programming-and-game-dev-10-class8375/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Pt11",
    },
    # 11 class
    {
        "num": "59",
        "recommended_courses_num": "70",
        "class_level": "11",
        "code_courses": "Pt11",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Программирование бизнес-приложений"
        " на Python. Уровень 3",
        "course_url": "https://iteen.by/programs/"
        "11-class/programming-and-game-dev-p-9-10-class/",
        "course_start": None,
        "number_hours": "108",
        "price": "2199,00",
        "recommended_courses": "PT1",
    },
    {
        "num": "60",
        "recommended_courses_num": "71",
        "class_level": "11",
        "code_courses": "Php9",
        "course_direction": "Web-технологии",
        "course_name": "Backend-разработка: PHP + SQL",
        "course_url": "https://iteen.by/programs/"
        "9-10-class/web-development-backend-9-10-class/",
        "course_start": None,
        "number_hours": "124",
        "price": "2299,00",
        "recommended_courses": "PD1",
    },
    {
        "num": "61",
        "recommended_courses_num": "72",
        "class_level": "11",
        "code_courses": "Mg9",
        "course_direction": "Дизайн",
        "course_name": "MagicArt: Photoshop + Illustrator",
        "course_url": "https://iteen.by/programs/"
        "9-10-class/design-ma-9-10-class/",
        "course_start": None,
        "number_hours": "80",
        "price": "1399,00",
        "recommended_courses": "CG4",
    },
    {
        "num": "62",
        "recommended_courses_num": "73",
        "class_level": "11",
        "code_courses": "Ux9",
        "course_direction": "Дизайн",
        "course_name": "UI/UX-дизайн: разработка сайтов",
        "course_url": "https://iteen.by/programs/"
        "9-10-class/design-9-10-class/",
        "course_start": None,
        "number_hours": "100",
        "price": "1999,00",
        "recommended_courses": "US1",
    },
    {
        "num": "63",
        "recommended_courses_num": "69",
        "class_level": "11",
        "code_courses": "Jv10",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Основы программирования на Java",
        "course_url": None,
        "course_start": None,
        "number_hours": "112",
        "price": "1999",
        "recommended_courses": "JC1",
    },
    {
        "num": "64",
        "recommended_courses_num": "70",
        "class_level": "11",
        "code_courses": "Pt7",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Практическое программирование",
        "course_url": "https://iteen.by/programs/"
        "11-class/programming-p-11-class/",
        "course_start": None,
        "number_hours": "108",
        "price": "2199,00",
        "recommended_courses": "PT1",
    },
    {
        "num": "65",
        "recommended_courses_num": "74",
        "class_level": "11",
        "code_courses": "PLab10",
        "course_direction": "IT-лаборатория",
        "course_name": "Teamwork: реализуй свой проект",
        "course_url": None,
        "course_start": None,
        "number_hours": "24",
        "price": "419,00",
        "recommended_courses": "SC0",
    },
    {
        "num": "66",
        "recommended_courses_num": "51",
        "class_level": "8",
        "code_courses": "Di8",
        "course_direction": "Дизайн",
        "course_name": "Digital иллюстрация",
        "course_url": "https://iteen.by/programs/7-8-class"
        "/design-d-7-8-class/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": "Bn9",
    },
    {
        "num": "67",
        "recommended_courses_num": None,
        "class_level": "11",
        "code_courses": "GD1",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Разработка мобильных игр на Unity",
        "course_url": "https://www.it-academy.by/course/"
        "razrabotka-igr-na-unity/razrabotka-mobilnykh-igr-na-dvizhke-unity/",
        "course_start": None,
        "number_hours": "128",
        "price": "2389,00",
        "recommended_courses": None,
    },
    {
        "num": "68",
        "recommended_courses_num": None,
        "class_level": "11",
        "code_courses": "CD1",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Программирование на С++",
        "course_url": "https://www.it-academy.by/course/"
        "c-game-developer/cd1-programmirovanie-na-s-/",
        "course_start": None,
        "number_hours": "92",
        "price": "1599,00",
        "recommended_courses": None,
    },
    {
        "num": "69",
        "recommended_courses_num": None,
        "class_level": "11",
        "code_courses": "JC1",
        "course_direction": "Программирование и Game Dev",
        "course_name": "Программирование на JAVA (базовый курс)",
        "course_url": "https://www.it-academy.by/course/java-developer/"
        "jd1-programmirovanie-na-java/",
        "course_start": None,
        "number_hours": "112",
        "price": "1999,00",
        "recommended_courses": None,
    },
    {
        "num": "70",
        "recommended_courses_num": None,
        "class_level": "11",
        "code_courses": "PT1",
        "course_direction": "Web-технологии",
        "course_name": "Комплексный курс по разработке"
        " веб-приложений на Python",
        "course_url": "https://www.it-academy.by/course/"
        "python-developer/pt-python-developer/",
        "course_start": None,
        "number_hours": "108",
        "price": "2199,00",
        "recommended_courses": None,
    },
    {
        "num": "71",
        "recommended_courses_num": None,
        "class_level": "11",
        "code_courses": "PD1",
        "course_direction": "Web-технологии",
        "course_name": "Комплексный курс по разработке веб-приложений на PHP",
        "course_url": "https://www.it-academy.by/course/java-developer/"
        "jd1-programmirovanie-na-java/",
        "course_start": None,
        "number_hours": "112",
        "price": "1999,00",
        "recommended_courses": None,
    },
    {
        "num": "72",
        "recommended_courses_num": None,
        "class_level": "11",
        "code_courses": "CG4",
        "course_direction": "Дизайн",
        "course_name": "Графический дизайн",
        "course_url": "https://www.it-academy.by/course/"
        "graficheskiy-dizayn/graficheskiy-dizayn/",
        "course_start": None,
        "number_hours": "80",
        "price": "1399,00",
        "recommended_courses": None,
    },
    {
        "num": "73",
        "recommended_courses_num": None,
        "class_level": "11",
        "code_courses": "US1",
        "course_direction": "Дизайн",
        "course_name": "Веб-дизайн и дизайн мобильных интерфейсов",
        "course_url": "https://www.it-academy.by/course/"
        "ui-ux-dizayner1/ui-ux-dizayner/",
        "course_start": None,
        "number_hours": "100",
        "price": "1999,00",
        "recommended_courses": None,
    },
    {
        "num": "74",
        "recommended_courses_num": None,
        "class_level": "11",
        "code_courses": "SC0",
        "course_direction": "Computer science",
        "course_name": "Основы Computer Science",
        "course_url": "https://www.it-academy.by/course/"
        "asp-net-developer/osnovy-computer-science/",
        "course_start": None,
        "number_hours": "24",
        "price": "419,00",
        "recommended_courses": None,
    },
    {
        "num": "75",
        "recommended_courses_num": None,
        "class_level": "11",
        "code_courses": "Sm9",
        "course_direction": "Дизайн",
        "course_name": "Дизайн. Реклама. SMM",
        "course_url": "https://iteen.by/programs/"
        "11-class/dizayn-11-klass-smm/",
        "course_start": None,
        "number_hours": "96",
        "price": "1344,00",
        "recommended_courses": None,
    },
]


class Command(BaseCommand):
    """
    Create a table with recommended courses if there are none.
    Takes args from environment variables.
    """

    def handle(self, *args: Any, **options: Any) -> None:
        if RecommendedCourse.objects.all().count() != len(data):
            RecommendedCourse.objects.all().delete()
            for _data in data:
                # added a link function between
                # the recommended course and the diriction model
                course_direction = Direction.objects.filter(
                    direction_name=_data.get("course_direction")
                ).last()

                recommended_curs_to_save = RecommendedCourse(
                    num=_data["num"],
                    recommended_courses_num=_data["recommended_courses_num"],
                    class_level=_data["class_level"],
                    code_courses=_data["code_courses"],
                    course_direction=course_direction,
                    course_name=_data["course_name"],
                    course_url=_data["course_url"],
                    course_start=_data["course_start"],
                    number_hours=_data["number_hours"],
                    price=_data["price"],
                    recommended_courses=_data["recommended_courses"],
                )
                recommended_curs_to_save.save()

            self.stdout.write("Recommended Course installed successfully.")
            return
        self.stdout.write("Recommended Course already exist.")
        return
